import fs from "node:fs";
import path from "node:path";
import process from "node:process";

const ROOT_DIR = process.cwd();

const QUESTIONS_PATH = path.join(ROOT_DIR, "data", "questions.json");

// مهم جدًا:
// لا نولّد إلى src/data.ts حتى لا نكسر بيانات الواجهة الحالية.
// هذا ملف آمن مستقل.
const OUTPUT_PATH = path.join(ROOT_DIR, "src", "data", "verified-data.generated.ts");

function fail({ reason, file }) {
  console.error("DATA GENERATION ERROR");
  console.error(`Reason: ${reason}`);
  console.error(`File: ${file}`);
  process.exit(1);
}

function readQuestionsJson() {
  if (!fs.existsSync(QUESTIONS_PATH)) {
    fail({
      reason: "questions.json does not exist.",
      file: QUESTIONS_PATH
    });
  }

  const raw = fs.readFileSync(QUESTIONS_PATH, "utf8");

  try {
    return JSON.parse(raw);
  } catch (error) {
    fail({
      reason: `Invalid JSON: ${error.message}`,
      file: QUESTIONS_PATH
    });
  }
}

function assertValidQuestionsData(questionsData) {
  if (!questionsData || typeof questionsData !== "object") {
    fail({
      reason: "questions.json root must be an object.",
      file: QUESTIONS_PATH
    });
  }

  if (!Array.isArray(questionsData.questions)) {
    fail({
      reason: "questionsData.questions must be an array.",
      file: QUESTIONS_PATH
    });
  }

  if (questionsData.questions.length === 0) {
    fail({
      reason: "questionsData.questions must contain at least one question.",
      file: QUESTIONS_PATH
    });
  }

  const seenIds = new Set();

  for (const [index, question] of questionsData.questions.entries()) {
    if (!question || typeof question !== "object") {
      fail({
        reason: `Question at index ${index} must be an object.`,
        file: QUESTIONS_PATH
      });
    }

    if (typeof question.id !== "string" || question.id.trim() === "") {
      fail({
        reason: `Question at index ${index} must have a non-empty string id.`,
        file: QUESTIONS_PATH
      });
    }

    if (seenIds.has(question.id)) {
      fail({
        reason: `Duplicate question id: ${question.id}`,
        file: QUESTIONS_PATH
      });
    }

    seenIds.add(question.id);
  }
}

function toTsLiteral(value) {
  return JSON.stringify(value, null, 2);
}

function buildGeneratedDataTs(questionsData) {
  const sourcePolicy = questionsData.sourcePolicy || {};
  const questions = questionsData.questions;

  const lessonMeta = {
    project: questionsData.project,
    lessonId: questionsData.lessonId,
    lessonTitle: questionsData.lessonTitle,
    schemaVersion: questionsData.schemaVersion
  };

  return `// AUTO-GENERATED FILE.
// DO NOT EDIT MANUALLY.
// Source: data/questions.json
// Generated by scripts/generate-data-ts.mjs
// Safe output path: src/data/verified-data.generated.ts

export const VERIFIED_SOURCE_POLICY = ${toTsLiteral(sourcePolicy)} as const;

export const VERIFIED_QUESTIONS = ${toTsLiteral(questions)} as const;

export const VERIFIED_QUESTION_COUNT = VERIFIED_QUESTIONS.length;

export const VERIFIED_LESSON_META = ${toTsLiteral(lessonMeta)} as const;
`;
}

function main() {
  if (OUTPUT_PATH.endsWith(path.join("src", "data.ts"))) {
    fail({
      reason: "Unsafe output path: generator must not overwrite src/data.ts.",
      file: OUTPUT_PATH
    });
  }

  const questionsData = readQuestionsJson();

  assertValidQuestionsData(questionsData);

  const outputDir = path.dirname(OUTPUT_PATH);
  fs.mkdirSync(outputDir, { recursive: true });

  const output = buildGeneratedDataTs(questionsData);
  fs.writeFileSync(OUTPUT_PATH, output, "utf8");

  console.log("DATA GENERATED OK");
  console.log("Output: src/data/verified-data.generated.ts");
  console.log(`Questions: ${questionsData.questions.length}`);
}

main();
